# -*- coding: utf-8 -*-
"""filter_ml_files.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EsJBV4_oDZzXtcO3aiK0tjMgc1hfMWo4
"""

!git clone https://github.com/PromaChow/ML_smells.git

!unzip /content/ML_smells/ml_repos_py_files.zip

import os
import ast
import shutil
import csv

# ML libraries
ML_LIBRARIES = {
    "tensorflow","torch","keras","sklearn","xgboost","lightgbm","catboost",
    "transformers","fastai","mxnet"
}

# Data science libraries
DATA_LIBRARIES = {
    "numpy","pandas","scipy","statsmodels"
}

# Visualization libraries
VIS_LIBRARIES = {
    "matplotlib","seaborn","plotly"
}

ML_KEYWORDS = {
    "fit","predict","train","train_test_split","DataLoader",
    "Sequential","RandomForest","LinearRegression",
    "LogisticRegression","KMeans","PCA"
}

MODEL_CLASSES = {
    "Module","Sequential","AutoModel","BertModel"
}


def analyze_file(filepath):

    score = 0

    try:
        with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
            tree = ast.parse(f.read())
    except:
        return 0

    for node in ast.walk(tree):

        if isinstance(node, ast.Import):
            for alias in node.names:
                name = alias.name.split('.')[0]

                if name in ML_LIBRARIES:
                    score += 3
                if name in DATA_LIBRARIES:
                    score += 2
                if name in VIS_LIBRARIES:
                    score += 1

        if isinstance(node, ast.ImportFrom):
            if node.module:
                name = node.module.split('.')[0]

                if name in ML_LIBRARIES:
                    score += 3
                if name in DATA_LIBRARIES:
                    score += 2

        if isinstance(node, ast.Call):

            if isinstance(node.func, ast.Attribute):
                if node.func.attr in ML_KEYWORDS:
                    score += 2

            if isinstance(node.func, ast.Name):
                if node.func.id in ML_KEYWORDS:
                    score += 2

        if isinstance(node, ast.ClassDef):
            for base in node.bases:
                if isinstance(base, ast.Attribute):
                    if base.attr in MODEL_CLASSES:
                        score += 4

    return score


def process_directory(input_dir, output_dir, csv_path):

    results = []
    kept_files = 0

    for root, dirs, files in os.walk(input_dir):

        for file in files:

            if file.endswith(".py"):

                full_path = os.path.join(root, file)

                score = analyze_file(full_path)

                if score >= 4:
                    label = "ML"
                elif score >= 2:
                    label = "Possibly ML"
                else:
                    label = "Non ML"

                rel_path = os.path.relpath(full_path, input_dir)
                new_path = os.path.join(output_dir, rel_path)

                if label != "Non ML":

                    os.makedirs(os.path.dirname(new_path), exist_ok=True)
                    shutil.copy2(full_path, new_path)

                    kept_files += 1

                results.append([full_path, score, label])

    # Save CSV
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["file", "score", "label"])

        for r in results:
            writer.writerow(r)

    print("ML / Data related files kept:", kept_files)


if __name__ == "__main__":

    INPUT_DIR = "/content/content/ml_repos_py_files"
    OUTPUT_DIR = "ml_filtered_repos"
    CSV_FILE = "analysis_results.csv"

    process_directory(INPUT_DIR, OUTPUT_DIR, CSV_FILE)

!zip -r 'ml_filtered_repos.zip' ml_filtered_repos/

